Dev
tataratat/gustaf pull request #16
Opened 2022-07-29 09:17 UTC by LinusKnecht

# new io.nutils

## Related issues
#7 relates to a new tool for gustaf - nutils conversions

## Description
This PR extends ```gustaf.io``` by a ```nutils``` tool. It can load and export simplex meshes (triangle and tetrahedron) from Gustaf to Nutils and vice versa. Functions can be called by

```
    load(fname)
    export(fname,mesh)
    to_nutils_simplex(mesh)
```
A ```io.mixd``` adaption was necessary. The new function ```as_mrng``` returns a mrng-like file.

2022-08-04 07:53 UTC, j042 requested changes
Thanks, nice feature!  
Let's try to stay close to [pep8](pep8.org) until we automate this process.

2022-08-04 07:53 UTC, j042 commented on gustaf/io/nutils.py
> +    Converts a Gustaf_Mesh to a Dictionary, which can be interpreted by nutils.mesh.simplex(**to_nutils_simplex(mesh)). Only work for Triangles and Tetrahedrons!
79 max line length.

2022-08-04 07:53 UTC, j042 commented on gustaf/io/nutils.py
> +    for index, row in enumerate(elements, start = 0):
```suggestion
    for index, row in enumerate(elements):
```
isn't default value for start always 0?

2022-08-17 14:01 UTC, CodeFloh reviewed
After we discussed the code I found a neat NumPy function that can replace some of your loops. This makes the code shorter and transfers some loops to NumPy.

Feel free to try this out or ignore it.

2022-08-17 14:13 UTC, CodeFloh commented on gustaf/io/nutils.py
> +        )
```suggestion
        bcs.update(
            {str(bi) : np.argwhere(bcs_sorted == bi)}
        )
```
Shorter option.. ;)

2022-09-07 05:12 UTC, j042 commented
Closing this one for now, feel free to reopen! @LinusKnecht

2022-09-07 05:12 UTC, closed without merging

2022-11-25 10:59 UTC, LinusKnecht commented on gustaf/io/nutils.py
> +    sort_array = sort_array.astype(int)
Thanks for the hints!